trigger:
  - master

pool:
    vmImage: 'Ubuntu-16.04'
    dockerHub: 'dockerhub'

variables:
  imageName: 'pipelines-javascript-docker'

steps:
- task: Docker@2
  displayName: Build and image
  inputs:
    repository: $(imageName)
    command: build
    Dockerfile: app/Dockerfile

- task: Docker@2
  displayName: Login to Docker Hub
  inputs:
    command: login
    containerRegistry: dockerhub
    
- task: Docker@2
  displayName: Push image
  inputs:
    containerRegistry: |
      $(dockerHub)
    repository: $(imageName)
    command: push
    tags: |
      acceptance

# - task: Docker@2
#   displayName: Push image
#   inputs:
#     containerRegistry: 'dockerhub'
#     repository: 'samjiks/pipelines-javascript-docker'
#     command: 'buildAndPush'
#     Dockerfile: 'app/Dockerfile'