trigger:
  - master

pool:
    vmImage: 'Ubuntu-16.04'

variables:
  username: 'samjiks'
  imageName: 'pipelines-javascript-docker'
  dockerHub: 'dockerhub'
  secondRegistry: 'MyAzureContainerRegistry'


steps:
- task: Docker@2
  displayName: Build and image
  inputs:
    repository: $(username)/$(imageName)
    command: build
    Dockerfile: app/Dockerfile
    tags: latest

# - task: Docker@2
#   displayName: Login to Docker Hub
#   inputs:
#     command: login
#     containerRegistry: $(dockerHub)
    
- task: Docker@2
  displayName: Push image
  inputs:
    containerRegistry: |
      $(dockerHub)
    repository: $(username)/$(imageName)
    command: push
    tags: | 
      latest

# - task: Docker@2
#   displayName: Push image
#   inputs:
#     containerRegistry: 'dockerhub'
#     repository: 'samjiks/pipelines-javascript-docker'
#     command: 'buildAndPush'
#     Dockerfile: 'app/Dockerfile'

- task: Docker@2
  displayName: Build and image
  inputs:
    repository: $(imageName)
    command: build
    Dockerfile: app/Dockerfile
    tags: latest

- task: Docker@2
  displayName: Push image to Azure Docker
  inputs:
    containerRegistry: 'MyAzureContainerRegistry'
    repository: '$(imageName)'
    command: 'buildAndPush'
    dockerfile: '**/Dockerfile'
    tags: |
      latest

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'